DROP TABLE IF EXISTS emp;

CREATE TABLE EMP(
EMP_ID INTEGER PRIMARY KEY,
EMP_NAME VARCHAR(50) NOT NULL,
EMP_EMAIL VARCHAR(50) NOT NULL,
EMP_MOBNO VARCHAR(10) NOT NULL,
EMP_CITY VARCHAR(20) NOT NULL
);



